# fly.toml app configuration file generated for kirbs on 2025-10-24T15:01:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kirbs'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'kirbs.ee'
  PORT = '8080'
  IMAGE_UPLOAD_DIR = '/data/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[mounts]]
  source = 'kirbs_data'
  destination = '/data'
  initial_size = '1gb'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
