defmodule Kirbs.Repo.Migrations.AddBagNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bags) do
      add :number, :bigserial, null: false
    end
  end

  def down do
    alter table(:bags) do
      remove :number
    end
  end
end
