defmodule Kirbs.Repo.Migrations.AddSoldAtToItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :sold_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:items) do
      remove :sold_at
    end
  end
end
