defmodule Kirbs.Repo.Migrations.RemoveYagaIdFieldsFromItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      remove :yaga_condition_id
      remove :yaga_materials_id_map
      remove :yaga_colors_id_map
      remove :yaga_category_id
      remove :yaga_brand_id
    end
  end

  def down do
    alter table(:items) do
      add :yaga_brand_id, :bigint
      add :yaga_category_id, :bigint
      add :yaga_colors_id_map, {:array, :bigint}
      add :yaga_materials_id_map, {:array, :bigint}
      add :yaga_condition_id, :bigint
    end
  end
end
