defmodule Kirbs.Repo.Migrations.AddForMonthToPayouts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payouts) do
      add :for_month, :date
    end

    # Backfill: copy month from sent_at (set to 1st of that month)
    execute "UPDATE payouts SET for_month = date_trunc('month', sent_at)::date"

    alter table(:payouts) do
      modify :for_month, :date, null: false
    end
  end

  def down do
    alter table(:payouts) do
      remove :for_month
    end
  end
end
