defmodule Kirbs.Repo.Migrations.AddUploadedAtToItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :uploaded_at, :utc_datetime_usec
    end

    # Backfill uploaded_at for existing items that are already on Yaga
    execute "UPDATE items SET uploaded_at = created_at WHERE status IN ('uploaded_to_yaga', 'sold') AND uploaded_at IS NULL"
  end

  def down do
    alter table(:items) do
      remove :uploaded_at
    end
  end
end
