defmodule Kirbs.Repo.Migrations.AddCompressedToImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images) do
      add :compressed, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:images) do
      remove :compressed
    end
  end
end
