defmodule Kirbs.Repo.Migrations.FixNullsDistinctClients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:clients, [:name, :phone, :email, :iban],
                     name: "clients_unique_client_index"
                   )

    create unique_index(:clients, [:name, :phone, :email, :iban],
             name: "clients_unique_client_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:clients, [:name, :phone, :email, :iban],
                     name: "clients_unique_client_index"
                   )

    create unique_index(:clients, [:name, :phone, :email, :iban],
             name: "clients_unique_client_index"
           )
  end
end
