defmodule Kirbs.Repo.Migrations.MakePhoneAndNameOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clients) do
      modify :name, :text, null: true
    end

    drop_if_exists unique_index(:clients, [:phone], name: "clients_unique_phone_index")

    alter table(:clients) do
      modify :phone, :text, null: true
    end

    create unique_index(:clients, [:name, :phone, :email, :iban],
             name: "clients_unique_client_index"
           )
  end

  def down do
    drop_if_exists unique_index(:clients, [:name, :phone, :email, :iban],
                     name: "clients_unique_client_index"
                   )

    alter table(:clients) do
      modify :phone, :text, null: false
    end

    create unique_index(:clients, [:phone], name: "clients_unique_phone_index")

    alter table(:clients) do
      modify :name, :text, null: false
    end
  end
end
