defmodule Kirbs.Repo.Migrations.AddCombinationGroup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :combination_group, :uuid
    end
  end

  def down do
    alter table(:items) do
      remove :combination_group
    end
  end
end
